#!/bin/bash
set -euo pipefail

DOCKER_USER="hkjn"
DOCKER_IMAGE="golang"

ARCH="$(uname -m)"
BUILD_DIR="$(mktemp -d)"

declare -A BASEIMAGES
BASEIMAGES[x86_64]=hkjn/alpine:x86_64
BASEIMAGES[armv7l]=hkjn/alpine:armv7l

BASEIMAGE=${BASEIMAGES[$ARCH]}
BUILD_DIR="$(mktemp -d)"
TAG="$DOCKER_USER/$DOCKER_IMAGE:$ARCH"

echo "Building $TAG in $BUILD_DIR.."
sed "s|ARG_FROM|${BASEIMAGE}|g" Dockerfile.in > $BUILD_DIR/Dockerfile
docker build -t $TAG "$BUILD_DIR/"
NO_PUSH=${NO_PUSH:-""}
[[ "$NO_PUSH" ]] || docker push $TAG
