FROM ARG_FROM

LABEL maintainer="Henrik Jonsson <me@hkjn.me>"

ENV GOLANG_VERSION 1.8.1
ENV GOLANG_SRC_URL https://golang.org/dl/go$GOLANG_VERSION.src.tar.gz
ENV GOLANG_SRC_SHA256 33daf4c03f86120fdfdc66bddf6bfff4661c7ca11c5da473e537f4d69b470e57
# https://golang.org/issue/14851

COPY no-pic.patch /
#     patch -p2 -i /no-pic.patch && \
#    rm -rf /*.patch && \

RUN set -eux && \
    apk add --no-cache ca-certificates git && \
    apk add --no-cache --virtual .build-deps bash gcc musl-dev openssl go && \
    export GOROOT_BOOTSTRAP="$(go env GOROOT)" && \
    wget -q "$GOLANG_SRC_URL" -O golang.tar.gz && \
    echo "$GOLANG_SRC_SHA256  golang.tar.gz" | sha256sum -c - && \
    tar -C /usr/local -xzf golang.tar.gz && \
    rm golang.tar.gz && \
    cd /usr/local/go/src && \
    ./make.bash && \
    apk del .build-deps && \
    adduser -D go -s /bin/bash && \
    chown -R go:go /usr/local/go/

ENV GOPATH /home/go
ENV PATH $GOPATH/bin:/usr/local/go/bin:$PATH

WORKDIR $GOPATH
USER go
