FROM ARG_FROM

LABEL maintainer="Henrik Jonsson <me@hkjn.me>"

RUN apk add --no-cache ca-certificates git go && \
    adduser -D go -s /bin/bash

ENV GOPATH /home/go
ENV PATH $GOPATH/bin:$PATH

WORKDIR $GOPATH

USER go
